version: '3.3'
services:
  db:
    container_name: postgis
    image: mdillon/postgis
    volumes:
      - postgres_data:/data/db
    ports:
      - "5432:5421"
  node_basic:
    container_name: node_app
    image: gmoralesc/node_basic
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db
volumes:
  postgres_data: