version: '3.3'
services:
  db:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_volume:/data/db
    ports:
      - "5432:27017"
  node_basic:
    container_name: node_app
    image: gmoralesc/node_basic
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db
volumes:
  mongo_volume: