version: '3.3'
services:
  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  node_basic:
    image: gmoralesc/node_basic
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db